import logo from '/public/logo.png';

function Hero() {
  return (
    <header className="w-full flex justify-center items-center flex-col">
      <nav className="flex justify-between items-center w-full mb-10 pt-3">
        <img src={logo} alt="AI Article Summarizer Logo generated by AI" className="w-36 object-contain" />
        <a
          href="https://github.com/matyaszednicek"
          target="_blank"
          className="rounded-full border border-gray-950 bg-gray-950 py-1.5 px-5 text-sm text-gray-50 transition-all hover:bg-gray-50 hover:text-gray-950"
        >
          Author
        </a>
      </nav>
      <h1 className="mt-5 text-5xl font-extrabold leading-[1.15] text-gray-950 sm:text-6xl text-center">
        Summarize Articles with <br className="md:hidden" />{' '}
        <span className="bg-gradient-to-r from-[#f8bb08] via-[#ee7001] via-40% to-[#fccf16] bg-clip-text text-transparent whitespace-nowrap">
          OpenAI GPT
        </span>
      </h1>
      <h2 className="mt-5 text-lg text-gray-600 sm:text-xl text-center max-w-2xl">
        Revolutionize content consumption with our AI-Powered Article Summarizer. Summarize just from a URL - transform
        lengthy articles into concise and easy-to-read summaries.
      </h2>
    </header>
  );
}

export default Hero;
